saving-and-investing:
  - how-to-save-money
  - savings-types
  - how-to-invest-money
  - investment-types
homes-and-mortgages:
  - buying-a-home
  - help-with-mortgages
  - types-of-mortgage
  - renting-and-letting
insurance:
  - home-insurance
  - car-insurance
  - travel-insurance
  - pet-insurance
  - help-with-insurance
  - life-and-protection-insurance
tools--resources:
  - calculators
  - comparison-tables
  - letter-templates
  - order-forms
  - free-printed-guides
  - videos
  - interactive-timelines
news:
Partners:
partners-universal-credit-banks:
partners-banks-universal-credit:
frontline-guide-test:
partners-uc-banks:
our-debt-work:
partners-uc-landlords:
resources-for-professionals-working-with-young-people-and-parents:
resources-for-professionals-supporting-young-people:
resources-for-professionals-supporting-parents:
research-and-toolkits-on-young-people-and-money:
benefits:
  - universal-credit
  - help-with-your-benefits
  - child-benefit
  - benefits-at-work
care-and-disability:
  - care-advice-and-help
  - paying-for-care
  - support-for-carers
  - illness-and-disability
debt-and-borrowing:
  - before-you-borrow
  - taking-control-of-debt
  - mortgage-and-rent-problems
  - help-with-loans
  - credit-cards-and-credit-ratings
budgeting-and-managing-money:
  - running-a-bank-account
  - managing-money
  - student-and-graduate-money
  - cutting-costs
births-deaths-and-family:
  - having-a-baby
  - maternity-and-paternity-rights
  - making-a-will
  - when-someone-dies
  - divorce-and-separation
cars-and-travel:
  - how-to-buy-a-car
  - running-a-car
  - selling-your-car
  - travel-money-and-sending-money-abroad
work-pensions-and-retirement:
  - jobs-and-tax
  - redundancy
  - pension-basics
  - types-of-pensions
  - automatic-enrolment
  - retirement-income-basics
  - types-of-retirement-income
