development:
  adapter: mysql2
  username: root
  database: cms_development
  pool: 5
  timeout: 5000
  encoding: utf8

test:
  adapter: mysql2
  username: root
  database: cms_test<%= ENV['TEST_ENV_NUMBER'] %>
  pool: 5
  timeout: 5000
  encoding: utf8

pipeline:
  adapter: mysql2
  database: <%= ENV['pipeline_db_name'] %>
  username: <%= ENV['pipeline_db_user'] %>
  password: <%= ENV['pipeline_db_password'] %>
  host: <%= ENV['pipeline_db_host'] %>
  port: <%= ENV['pipeline_db_port'] %>
  pool: 5
  timeout: 5000
  encoding: utf8

# We have this database configuration because we use the gem `js-routes` to allow us to access Rails routes from
# our JavaScript assets. Normally you configure the Rails application's `initialize_on_precompile` setting to false
# but `js-routes` requires an initialised Rails application so we include a database config for the `assets`
# environment to get Rails to initialize when we run `rake assets:precompile`.
assets:
  adapter: sqlite3
  database: db/assets.sqlite3
  pool: 5
  timeout: 5000
